### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by rezgarshakeri** [OrchardLANL/DPFEHM.jl#16]
In the current documentation (the README file), it is stated that "DPFEHM supports the groundwater flow equations (single phase flow), Richards equation (air/water), the advection-dispersion equation, and the 2d wave equation".
- I think it would be helpful to add those equations to the documentation. Only Richards equation is linked to the [wikipedia](https://en.wikipedia.org/wiki/Richards_equation)  which doesn't match the description. For example, in README you talk about relative permeability and storage, but in that link they are not defined. 
- It is mentioned in the paper "DPFEHM uses a two-point flux approximation finite volume scheme". It would be also helpful to add this to the documentation and perhaps its discretized formulation.
- It would be good to add purpose, input, output and variables that are needed inside each function in the DPFEHM.jl/src files. And adding some inline comments would help the user to contribute  in the future.

Refs https://github.com/openjournals/joss-reviews/issues/4560

**Comment by omalled** [comment]
I updated the README to address the first couple bullets: putting the Richards equation in better context with respect to the Wikipedia article and describing the two point flux a bit.

I agree it would be good to add more comments in the source. It could be tricky to do it since many of the functions are generated using metaprogramming. Let me think a bit if there's a good way to deal with that.

**Comment by omalled** [comment]
The code has now been updated with much better documentation throughout. In combination with the previous changes, I think this addresses each of the three bullets. So I'm closing this issue.

**Comment by rezgarshakeri** [comment]
Sorry for my late reply, thanks.
